### ISSUE TITLE
Publish using ARM rest apis

### ISSUE THREAD

**Issue by kieranross89** [Azure/api-management-developer-portal#1039]
What is hopefully a couple of quick questions.

My team has had some success in automation the vast majority of the custom content we wanted deployed to the managed developer portal. Most of this has been achieved using the ARM rest API. 

Is there a reason that a POST to https://<servicename>.developer.azure-api.net/publish works but does not appear to be an equivalent call exposed via the ARM https://management.azure.com endpoints? I am sure we have just missed something here so some pointers would be appreciated! 

This leads me onto my second question if we do need to rely upon the APIM management API (which we are hoping to avoid). Would this be the correct call for disabling/enabling the API? 

https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/tenantaccess/update

We were hoping we could simply disable the API once published rather than leaving it enabled. Unfortunately documentation is not very clear on this one. 

Many thanks 
Kieran

**Comment by mikebudzynski** [comment]
1. We will be soon releasing ARM API endpoint for publishing the developer portal. The ETA is hopefully December, but it may slip to January.
2. Yes, you can disable the management endpoint.
3. On another note, we have two more improvements to remove dependency on the management endpoint altogether:
a. We will soon be migrating the administrative calls in the developer portal to use ARM. ETA is 1-3 months.
b. We will soon be introducing a new endpoint for developer portal runtime API calls (for example, to fetch list of APIs). ETA is 2-4 months.

**Comment by dersia** [comment]
Hi @mikebudzynski,
is there yet a release date for V3 publishing?

**Comment by mikebudzynski** [comment]
1-2 months, pending on the API Management service (backend) release roll-out.

**Comment by azaslonov** [comment]
Most of the public services were upgraded. The functionality should be working now.

**Comment by AnRei123** [comment]
For our test instances, publishing the portal contents with the publishing scripts still does not work yet.

**Comment by kieranross89** [comment]
Is the new publish endpoint documented anywhere? Thanks.

**Comment by mikebudzynski** [comment]
> Is the new publish endpoint documented anywhere?

https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-06-01-preview/portalrevision/createorupdate

**Comment by azaslonov** [comment]
@AnRei123, do you have any errors? Are you following the documentation (like Mike has provided above)?

**Comment by AnRei123** [comment]
[https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-06-01-preview/portalrevision/createorupdate](https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-06-01-preview/portalrevision/createorupdate)
Why does this API "**Portal Revision - Create Or Update**" publishes the portal? The documentation does not state it. The documentation just states that with the help of this API you are able to add or update a revision state or description. Could you add further contextual information in the introduction of this API where, when and why to use it? The documentation is confusing without understanding the use case. Especially, if the purpose of this API would be also or especially to publish the content.

**Comment by AnRei123** [comment]
@azaslonov: To be honest, currently I still use the V2 scripts and I still get an error message. But I am interested in understanding if I should migrate to the ARM rest APIs with V3? Would the V2 scripts still be supported in future?

**Comment by kieranross89** [comment]
> > Is the new publish endpoint documented anywhere?
> 
> https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-06-01-preview/portalrevision/createorupdate

Thanks that works. Although I noticed it takes an awful long time to publish ( a number of hours). My test instances use the developer tier, is this due to their being no SLA or should I expect to see similar in our prod instance?

**Comment by kieranross89** [comment]
@azaslonov / @mikebudzynski so after a bit of further experimentation I have noted the following behaviour and not sure if the initial manual publish would be expected or not.

The process is as follows:
* Deploy a fresh APIM instance - via our existing arm template with the API versions updated
* Our pipeline then updates our dev portal content once the ARM template is completed and attempts to publish using the new endpoint using az rest and this results in a portal revision in a failed state. Our dev portal remains unpublished with the default page about publishing the dev portal. 
* A manual publish is required via the Azure portal 
* The pipline can then be rerun with the successful creation of the portal revision and our custom content is published and available via the dev portal
```
{
  "value": [
    {
      "id": ".../Microsoft.ApiManagement/service/gsppgde5managementinformation/portalRevisions/e513ec0d-6540-46c6-9878-018c2a15cb23",
      "type": "Microsoft.ApiManagement/service/portalRevisions",
      "name": "e513ec0d-6540-46c6-9878-018c2a15cb23",
      "properties": {
        "description": "revision e513ec0d-6540-46c6-9878-018c2a15cb23",
        "statusDetails": null,
        "status": "failed",
        "isCurrent": false,
        "createdDateTime": "2021-04-12T12:23:45.763Z",
        "updatedDateTime": "2021-04-12T12:24:00.203Z"
      }
    },
    {
      "id": "...Microsoft.ApiManagement/service/gsppgde5managementinformation/portalRevisions/03cb0adf-9099-4f66-a918-7cebfa88d5c2",
      "type": "Microsoft.ApiManagement/service/portalRevisions",
      "name": "03cb0adf-9099-4f66-a918-7cebfa88d5c2",
      "properties": {
        "description": "revision 03cb0adf-9099-4f66-a918-7cebfa88d5c2",
        "statusDetails": null,
        "status": "completed",
        "isCurrent": true,
        "createdDateTime": "2021-04-12T14:17:46.263Z",
        "updatedDateTime": "2021-04-12T14:18:04.02Z"
      }
    }
  ],
  "count": 2
}
```
I was hoping that the new update would also negate the need to carry out the manual publish step.

**Comment by ErikMogensen** [comment]
I have the same issue.

At least you get a confirmation now what happened with the request instead of having to wait a long time to determine the outcome.

**Comment by AnRei123** [comment]
Till when will the v2 scripts be supported? We haven´t started to move to the ARM templates yet, and I would prefer that both approaches could be supported in parallel.
Or that you at least offer GUI buttons in the APIM portal additionally to enable manual backups and uploads for test reasons. But to keep the v2 scripts for a longer period of time with a working publishing approach would be preferred.

**Comment by azaslonov** [comment]
@AnRei123, oh no worries about it, many people still use it, so we won't drop it just like that. Most likely we'll just make v3 backward compatible with v2, before deprecating it.

**Comment by azaslonov** [comment]
@kieranross89 please send us your service names, I'll take a look into the logs.

@ErikMogensen, I'm following up with you offline.

**Comment by kieranross89** [comment]
> @kieranross89 please send us your service names to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com), I'll take a look into the logs.
> 
> @ErikMogensen, I'm following up with you offline.

Done. 

Thanks 🙂

**Comment by ErikMogensen** [comment]
Publishing works for me if the portal has gotten content, so as far as I concerned I am done with this issue.

**Comment by azaslonov** [comment]
Alrighty, I think we can close it now. Feel free to re-open shall you face other issues, folks.

**Comment by ErikMogensen** [comment]
Thanks for great work in finding the explanation for this @azaslonov!
