### ISSUE TITLE
Not able to Add Table Row to Existing Tables in Developer Portal

### ISSUE THREAD

**Issue by desireehanuman** [Azure/api-management-developer-portal#2033]
**Every bug report should have precise description and reproduction steps; console traces or source code references are appreciated.**

**For assistance requests, contact Azure support or submit a post [on Stack Overflow](http://aka.ms/apimso). We don't provide support through GitHub Issues. Feature requests can be raised [on the Azure Feedback Forum](https://aka.ms/apimwish).**

## Bug description

A clear and concise description of the bug.

## Reproduction steps

1. Go to the Developer Portal
2. Try to Edit an Existing Table. 
3. Increase the number of rows by 1
4. See error. Nothing happens. 

## Expected behavior

Before, when I would try to edit a table and add more rows, I would increase the number of rows and the added rows would appear at the bottom of the table

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

od-qa1 (Tecsys)

## Environment

We have tried the latest versions of Firefox, Chrome, and Edge.

**Comment by azaslonov** [comment]
@desireehanuman, this issue has been fixed in #2027. The managed portals will get the fix soon.

**Comment by desireehanuman** [comment]
@azaslonov Hello again, I went to check again today and it's still not working. Do you know when the managed portal will be fixed?

**Comment by desireehanuman** [comment]
> @desireehanuman, this issue has been fixed in #2027. The managed portals will get the fix soon.

Do you have any estimation as to when the managed portals will get the fix. It's been over a month.

**Comment by desireehanuman** [comment]
@azaslonov Hello again, the portal is still unable to add rows to the tables. When will this be fixed?

**Comment by Amal50** [comment]
@azaslonov Hi there,
Any idea when the fix will be deployed? it blocks our production deployment and causes issues to our clients. We've been waiting long time to get this issue fixed

**Comment by FXZFun** [comment]
@azaslonov Our portal is still unable to edit the tables as well. Do you have an updated timeline on the release?

**Comment by azaslonov** [comment]
@Amal50, @FXZFun, apologies for the delay folks. The fix is being rolled out, current ETA to reach every region is 2/10.

**Comment by desireehanuman** [comment]
@azaslonov The fix still hasn't been deployed to our portal. Is there an updated ETA?

**Comment by azaslonov** [comment]
The fix has been deployed to all public regions. Thank you for patience folks.
