### ISSUE TITLE
Package.json / Package-lock.json out of sync. NPM install fails for 2.22.0

### ISSUE THREAD

**Issue by nahojs** [Azure/api-management-developer-portal#2046]
## Bug description

NPM install exits with NPM e401 - auth fails for a few packages/modules (w3c-keyname ) in release 2.22.0. 

 I managed to solve this issue by manually pull in ‘package-lock.json’ from master branch, and then it works. 

## Reproduction steps

Clone repo and checkout 2.22.0
Run NPM install

## Expected behavior

NPM install should not throw e401 error

## Is your portal managed or self-hosted?

 Self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.22.0

## API Management service name

[e.g., contoso-api]

## Environment

 Windows 10.

## Additional context

NPM version 8.19.2
Node.js v18.12.1

**Comment by JMach1** [comment]
@nahojs, thank you for reporting the issue. Do I understand correctly that the issue was resolved and no further assistance is needed? 
In case you receive an e401, it's always best to make sure you have latest package-lock.json without any changes. Also running `npm ci` might help.

**Comment by nahojs** [comment]
@JMach1 I made a work-around. The issue with release 2.22.0 still exists (It doesn't build).

**Comment by erwinkramer** [comment]
Same issue here. What was your work around @nahojs ?

**Comment by erwinkramer** [comment]
I see your work-around, thanks
