### ISSUE TITLE
API Gallery - heavily truncated API description

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#2260]
## Bug description

For our API descriptions we noticed that some are heavily truncated to just a few words.
![image](https://github.com/Azure/api-management-developer-portal/assets/58420097/87dcdca9-148c-437c-8c2d-f473b6c17392)

After testing around we noticed that for a certain range of characters the truncation is just not working right:

If the length of the API description is greater than 250 characters the overview description on the API Overview page is truncated very badly.

It seems that the truncation length scales with the length of the description:
A long text has a longer truncation than a short text 
Therefore, short texts that are truncated have a very short truncated description -> see the 3 word description in the screenshot
A description of e.g. 600 characters is truncated to 363 characters while a description of 363 characters is truncated to 128 characters.

I tested various string lengths and these are the results:

- 0-250: Good display of the description
- 251 - ~350:  Very short description (the 350 is only as a reference as it contains atleast some words that can be put into context)
- 350 - ...: Better with the truncation scaling with the description length

Similar like #2259 this causes the user more mental load to understand our offers by having to click though all APIs without a useful overview.

## Reproduction steps

1. Add different description lengths to the OpenAPI Specification
2. Compare results for different lengths
3. See the behavior

## Expected behavior

- Description and rules regarding the truncation (especially the scaling of the description length and the truncation)
- A min length for truncated descriptions , or
- Raising the character limit before truncating the text

## Is your portal managed or self-hosted?

Managed

**Comment by ZarTrox** [comment]
Known Affected Widgets: List of APIs

**Comment by malincrist** [comment]
Hello @ZarTrox , thanks for reaching out. It appears that the issue you are describing has been fixed by #2140.
However, please note that it hasn't been deployed for managed portals yet (ETA is end of August).

**Comment by Elivoll** [comment]
Hello, 

You mentioned the ETA for this issue is end of August., however it is not fixed yet.
I wanted to bring to your attention the urgency of the situation regarding the bug in the code. Could you please check when this issue will be resolved, when the new code will be released, and when it will be rolled out?

Thank you!

**Comment by elisabethvolkinshtein** [comment]
Hello, 
I would like to bring to your attention that we urgently need a solution for this issue.
This issue is still not fixed.

Thank you!
