### ISSUE TITLE
Links to some elements don't work for objects with inheritance

### ISSUE THREAD

**Issue by josealbertocoronado** [Azure/api-management-developer-portal#2290]
**Every bug report should have precise description and reproduction steps; console traces or source code references are appreciated.**

**For assistance requests, contact Azure support or submit a post [on Stack Overflow](http://aka.ms/apimso). We don't provide support through GitHub Issues. Feature requests can be raised [on the Azure Feedback Forum](https://aka.ms/apimwish).**

## Bug description

For some properties in an object that inherits from a different object, the links to some of the properties don't work. The element is not even loaded in the page.

## Reproduction steps

1. Go to ig-weu-dev-integration-apim developer portal.
2. Go to the API called "Gateway API Services".
3. Go to the "multitypeRequest" endpoint.
4. Navigate to "firstNotificationMotor" object.
5. Click in "brokerReference" property, link doesn't work. Interestingly some other similar fields work smoothly (f.i. "brokerName").

## Expected behavior

Links to the different elements in a object always work.

## Is your portal managed or self-hosted?

Managed

## API Management service name

ig-weu-dev-integration-apim

**Comment by JMach1** [comment]
Hello @josealbertocoronado 
I reproduced the issue, we'll work on fixing the bug. 
ETA next portal release in ~ 1 month 
Thank you for reporting it!

**Comment by josealbertocoronado** [comment]
Lovely. Thanks for that.

**Comment by josealbertocoronado** [comment]
Hi, sorry revisiting this ticket but unfortunately the fix hasn't worked.

Links for properties like "brokerReference" (see description above) still don't work.

Can you please take a look? Cheers.

**Comment by josealbertocoronado** [comment]
Hi @jsorohova , any update on this, please? It's quite blocking now, as users complain about the bad experience they're getting with the developer portal when they can't navigate to the different properties.

**Comment by josealbertocoronado** [comment]
Hi @jsorohova , I'm not sure whether it's the same issue or something new but now I'm experiencing a different issue with links.
No single link works now. Whatever link I click it always takes me to the top of the page. It's happening since not too long ago, so i reckon it's related to the last release.

You just reproduce it by going to our company portal and clicking any link: https://ig-weu-dev-integration-apim.developer.azure-api.net/

This is quite blocking as the image we expose to our customers is quite poor, so I would really appreciate if you can take a look with some urgency, please.

Cheers.

**Comment by josealbertocoronado** [comment]
Morning @jsorohova .
Any update on this? Month and a half since last update. We're giving very poor image to our customers.

**Comment by josealbertocoronado** [comment]
Hi @jsorohova .
Bumping up this. Any update, please? Still an issue.

**Comment by jsorohova** [comment]
Hello @josealbertocoronado, I just merged this fix. Unfortunately, it will take some time for this fix to make it to production. It will be included in the release 2.27. ETA is around a month. Sorry for inconveniences.

**Comment by josealbertocoronado** [comment]
Hi.
I'm checking this issue and I think it's now worse than before.
Links still don't work but now objects don't show up either. So we're moving back instead of forward unfortunately.

That's it. We cannot keep using this product, I reported this issue on Sept 2023. The image we give to our customers is so poor. If not fixed for next week you will lose a customer.

**Comment by sthirthala** [comment]
@josealbertocoronado  this has been fixed in the latest release just deployed. Hope this is resolved on your side as well.

**Comment by josealbertocoronado** [comment]
Morning @sthirthala .
Just tried and it's not fixed. Links still don't work, and the different properties of the objects don't show up.
This is the resource I try with: https://ig-weu-dev-integration-apim.developer.azure-api.net/
Happy to have a chat.
