### ISSUE TITLE
Publishing the portal doesn't work

### ISSUE THREAD

**Issue by kdelgadod** [Azure/api-management-developer-portal#239]
Since the last week i was published new content (new images and new texts) iin my new azure api managment developer portal and since yesterday all changes are not show. The only message is " The website is being published..." and nothing else happens.  Is there a reported issues? 

Tha last week works normal.

**API Management service name**
new developer portal

**Environment**
Azure

**Comment by mikebudzynski** [comment]
@kdelgadod Could you please:

1. Retry and see if the error still persists
2. If it does, provide us with the service name and reproduction steps

**Comment by kdelgadod** [comment]
I retry and nothing happens
![pub](https://user-images.githubusercontent.com/54553759/67710400-e0478800-f98d-11e9-8a07-d5d36805a6bb.png)

**Comment by kdelgadod** [comment]
> @kdelgadod Could you please:
> 
> 1. Retry and see if the error still persists
> 2. If it does, provide us with the service name and reproduction steps

I retry and nothing happens

![pub](https://user-images.githubusercontent.com/54553759/67719920-c5324380-f9a0-11e9-81f9-f0aafbb36541.png)

**Comment by mikebudzynski** [comment]
Thanks for the reports, we will investigate the problems as soon as possible

**Comment by mikebudzynski** [comment]
The fix has been deployed and is being rolled out. Your service should be upgraded by the end of the week.

Please, reopen the issue if the problem still persists after that.

**Comment by mikebudzynski** [comment]
This should already be fixed for most Developer and all new services. It's still being rolled out to higher tier API Management services.

**Comment by SahinOzdemir** [comment]
The issue still exists on the developer tier. When I Publish 404 page, the changes arent being reflected in the live environment.

**Comment by azaslonov** [comment]
Hi @SahinOzdemir, could you please email me your APIM service name at alzaslon@microsoft.com, I'll check if it has received the latest fixes. Thank you.

**Comment by SahinOzdemir** [comment]
Just sent you an email @azaslonov

**Comment by mikebudzynski** [comment]
Update: the release is still being rolled out. We expect the rollout to finish by Nov 22nd.

**Comment by techports** [comment]
Just APIs are listing in new developer;s dashboard. Unable to open APIs and Products are also not listed,

**Comment by SahinOzdemir** [comment]
> Just APIs are listing in new developer;s dashboard. Unable to open APIs and Products are also not listed  

I noted the same.  @techports @mikebudzynski

**Comment by mikebudzynski** [comment]
@techports , @SahinOzdemir - can you please open a separate Issue with the bug report? Please include reproduction steps and the answers to my questions below:

1. I don't understand what you mean by "developer's dashboard". The user profile page doesn't show subscriptions to Products?
2. Why would you like to see open Products listed in the portal, if users can't subscribe to them?
3. What do you mean as an open API? An API that is part of an open Product?

**Comment by mikebudzynski** [comment]
The new release with the portal improvements has been rolled out to most of the API Management services.
