### ISSUE TITLE
Redirect anonymous users to sign-in page causes infinite redirect loop

### ISSUE THREAD

**Issue by krispenner** [Azure/api-management-developer-portal#404]
When I enable the "Redirect anonymous users to sign-in page" option and navigate to the developer portal, the sign in page just keeps redirecting to itself infinitely.

This does not always happen. It happened at first in MS Edge followed by Chrome. Now Edge is working properly and an Incognito Chrome instance also works correctly but my regular Chrome tab continues to redirect. This may have something to do with me using the admin design mode of the portal in Chrome previously and that admin authentication is getting confused with my test user authentication. If that is a known side effect then maybe I just need to ensure I use an Incognito tab every time for testing my API user.

So **work around** is:
Use Incognito tab for testing an API user if using Admin Design Mode previously/recently.

I hope the below screenshot of chrome's network traffic might help. Let me know if I can provide anything else.

![image](https://user-images.githubusercontent.com/8837910/72198617-05706200-33e5-11ea-8005-aa14c8699fcc.png)

**Comment by azaslonov** [comment]
Hi @krispenner, I could not reproduce this, can you please provide step-by-step instructions?

**Comment by krispenner** [comment]
Interestingly today I'm getting a very different result which is still an issue for me.

## Steps

Using Chrome or Edge, I get the same result.

1. A side note on this is that I have both `Azure Active Directory` and `Username and password` identity providers enabled, maybe you need to do the same...

2. Enable 'Redirect anonymous users to sign in page'
![image](https://user-images.githubusercontent.com/8837910/72284177-33c48c00-35f5-11ea-8c89-f8f368397a24.png)

3. Go to API Management Overview page and click the 'Developer Portal' link which opens the new Developer Portal in a new tab.
![image](https://user-images.githubusercontent.com/8837910/72284409-c2390d80-35f5-11ea-941a-4f02c343b8dd.png)

4. Close **all** tabs.

5. Open new browser instance, but same brand (Chrome or Edge) as before.

6. Navigate to developer portal.

7a. **Previously** I would just continually redirect back to the sign in page indefinitely until I hist Stop/Esc which would render the page useless, hitting refresh would start the redirect loop again.

7b. **Currently** I now receive the below error pop up.
![image](https://user-images.githubusercontent.com/8837910/72284622-4b504480-35f6-11ea-9958-ae46ec36be2d.png)

8. Wait 10 minutes or so.

9. Navigate to developer portal.

10. Can now sign in as a user.

## Expected

7. Can now sign in as a user.

## Notes

I can see this is obviously an issue with a cookie or some authentication cache. The easy work around is to just use an Incognito or Private tab when testing an API user. However, I would expect that closing the entire browser should completely clear any auth session cookie cache and allow me to log in immediately as an API user.

**Comment by azaslonov** [comment]
Understood. Thank you, we'll work on it.

**Comment by dvXcode** [comment]
That is annoying bug.  Any idea when it will be solved and released?

**Comment by ygrik** [comment]
This issue was fixed with the current release, please republish dev portal to get the latest updates.

**Comment by mrcunninghamz** [comment]
@ygrik 

I think this is still a problem. In incognito I am unable to go to any other page than the login page and in just normal chrome i get redirect loop. I have recently published the dev portal, unless maybe I'm not publishing correctly?

Thanks.

**Comment by BobbyCGD** [comment]
Looks like this is related to #822
