### ISSUE TITLE
Session not persisted across browser tabs

### ISSUE THREAD

**Issue by ikteru** [Azure/api-management-developer-portal#532]
## Bug description

When I tried to share the link to the "API Details" page of one of the APIs I have available through the developer portal, I noticed that when you open said link in a new browser tab or window, you do get the API Details page, but it acts as if there are no APIs available. But that's not the problem, the problem is that the session is not persisted across browser tabs or windows. 
Therefore, even if I share a link with my clients like the following: 
`https://test.developer.azure-api.net/api-details#api=echo-api&operation=create-resource
`They will get an "API Details" page with no APIs and where they have to login again even if they previously logged in. 

## Reproduction steps

While investigating this I tried the following:

1. Open an incognito window
2. Go to the link:  `https://test.developer.azure-api.net/`, logged in to the developer portal.
3. Opened a new tab and tried visiting the same link `https://test.developer.azure-api.net/`.

## Expected behavior
I expected to still be logged in. 

## Actual behavior
I was still logged in the first tab, however in the second tab, I was not logged in.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

[e.g., contoso-api]

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by azaslonov** [comment]
Hi @ikteru, thanks for reporting the issue. We'll fix that.

**Comment by ikteru** [comment]
Is the fix going to be pushed to the hosted version? If yes, when do you think that's happening?

**Comment by ygrik** [comment]
The fix will be deployed for managed portals approx in 2-3 weeks.

**Comment by ygrik** [comment]
This issue was fixed with the current release, please republish dev portal to get the latest updates.

**Comment by ikteru** [comment]
I republished the portal, the issue is still present. ( More issues popped up like the "scrollable menu" widget now looks worse )

**Comment by ikteru** [comment]
The update also broke the "Styles" section of the developer portal designer, it looks like a mess.

**Comment by azaslonov** [comment]
Oh, I guess we'll need your service ID to see what's going on. Can please send it here: apimportalfeedback@microsoft.com
