### ISSUE TITLE
[Urgent] Publishing Portal after new release breaks AAD

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#822]
## Bug description

If one publishes a DevPortal Instance after the latest release (07.08.20) log-in via the AAD button does not work.
The page loads but nothing happens at all. Also one cannot navigate through the URL.

## Reproduction steps

1. Go to the published version of a DevPortal Instance
2. Get directed to the Sign-In page
3. Press the AAD button
4. Enter your credentials
5. Wait
6. See that nothing happens
7. (If the Portal is resetted it is in a refresh loop)

## Expected behavior

It should work like before the new release.

## Is your portal managed or self-hosted?

Managed

## Additional context

![2020-08-10_12-59-07](https://user-images.githubusercontent.com/58420097/89776104-7e65a280-db09-11ea-8165-38663290fee8.gif)

**Comment by TimMenze** [comment]
We have the same issue with our developer portal after publishing portal, but we are using simple username & password authentication.

**Comment by mikebudzynski** [comment]
Thanks for reporting, we will start investigating as soon as possible.

**Comment by mikebudzynski** [comment]
@ZarTrox we identified an issue with AAD: https://github.com/Azure/api-management-developer-portal/pull/824 but:
1. We were able to reproduce it only in the self-hosted portals, not managed
2. The website doesn't reload infinitely as you show in the screenshot

Can you make sure there weren't any changes in your AAD / networking setup? If there weren't any, can you provide us with the service name and network traces via email to apimportalfeedback@microsoft.com?

@TimMenze what's the problem with the username and password sign-in? Can you provide us with reproduction steps? It doesn't seem to be related.

cc: @ygrik

**Comment by TimMenze** [comment]
@mikebudzynski sure, please find some more information below.

### Reproduction steps

1. Open Dev-Portal URL
2. Redirect to Sign-In page
3. Enter Username + Password
4. Press "Sign In" Button
5. Wait
6. Infinite Refresh Loop to Sign-In page

![login_problems_apim_developer_portal](https://user-images.githubusercontent.com/58325404/89862873-1d8da700-dba9-11ea-9aac-8504155c961c.gif)

**Comment by ygrik** [comment]
@TimMenze did you try to remove cookies and clear session?

**Comment by AnRei123** [comment]
Yes.

Some hours ago, I received that further instances for development are 
impacted know. They cannot log in anymore. The crazy thing is that I tested 
nearly all instances this morning, most of them still worked for me.
We did the test with the inkognito mode of the Chrome browser. Once, 
additionally I cleared the cache of the browser. This is really a bad 
situation. We do not only use the portal by ourselves. Customers do also 
rely on them. Our product timeline depends on accessing the portals of 
several instances.


Viele Grüße,
Angelika


--- Original-Nachricht ---
Von: Igor O
Betreff: Re: [Azure/api-management-developer-portal] [Urgent] Publishing 
Portal after new release breaks AAD (#822)
Datum: 11. August 2020, 19:28
An: Azure/api-management-developer-portal
Cc: AnRei123, Manual



@TimMenze <https://github.com/TimMenze> did you try to remove cookies and 
clear session?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/api-management-developer-portal/issues/822#issuecomment-672117326> 
, or unsubscribe

**Comment by TimMenze** [comment]
@ygrik yes I did. Same problem :(

**Comment by MelHarbour** [comment]
We are also experiencing this issue with it looping after signin on AAD.

**Comment by LockTar** [comment]
Some problem here! No working developer portal anymore

**Comment by olandese** [comment]
we are experiencing the same problem. Not able to login with AAD anymore

**Comment by mikebudzynski** [comment]
We have hotfixed all regions, please republish your portal. Apologies for the inconvenience. 

We'll create a new self-hosted release shortly.

**Comment by olandese** [comment]
I just did a republish, but the problem is still there (West-Europe)

**Comment by mikebudzynski** [comment]
We redeployed the fix, can you please check again?

**Comment by AnRei123** [comment]
Unfortunately, for the two affected instances (managed) it still does not work. I cleared the cache in the Chrome browser. Closed the browser and opened it again. Published the current version. Opened the web url in the incognito mode. But still same behavior. Only the sign-in page is shown after adding the credentials to the sign-in dialog. For the legacy portal of the impacted instances, this issue does not show up. The sign-in for the legacy portal with the aad button is possible w/o any problem. This issue only occurs for two of our instances for the new dev portal after I have done content modifications and after I have published the content. I also checked the behavior with the Firefox browser this morning. Same issue.

**Comment by olandese** [comment]
same here, I republished the portal, open it in an incognito window but the problem is still there

**Comment by butsona** [comment]
We are also experiencing issues with sso. After clicking the AAD Signin the popup is shown. Once credentials are entered the popup disappears but the main form is not refresh. If we manually refresh the user is logged in. But users are unlikely to manually refresh.

Please can you make sure changes are tested before releasing. Especially when this effecting our clients.

**Comment by olandese** [comment]
I was able to solve the problem disabling the "Redirect anonymous users to sign-in page".

![image](https://user-images.githubusercontent.com/1708128/90109170-b6f4be80-dd4b-11ea-8347-c7c0ad1e0598.png)

If the option is enabled after logging in with AAD the users seems still to be anonymous and no content is shown. 
With the option disabled (and after logging in with AAD) we are able to see the API's and Products.
The Products and API's are shown only if an authenticated user is in a specific APIM group, that's why we can temporary disable the option. 

Obviously this is not what we want, it's just a temporary work around

**Comment by olandese** [comment]
Is there any news about this issue?

**Comment by mikebudzynski** [comment]
The problem was on the backend side of API Management (cookie wasn't set on redirect) and the fix will be rolled out in the next few days.

**Comment by olandese** [comment]
> The problem was on the backend side of API Management (cookie wasn't set on redirect) and the fix will be rolled out in the next few days.

I just republished the portal, but the problem is still there. Is the fix rolled out in West-Europe?

**Comment by azaslonov** [comment]
Hi @olandese, backend hasn't been deployed to West Europe yet, but it looks like this bug affects only specific services, so, to make sure this is the same case, could you please capture network traces into HAR file and send it to us apimportalfeedback@microsoft.com?

**Comment by tomilaakkonen** [comment]
@azaslonov It affects if you force anon users to login. If you disable the option then the problem doesn't occur. We are using West Europe and still having the issue.

**Comment by olandese** [comment]
> @azaslonov It affects if you force anon users to login. If you disable the option then the problem doesn't occur. We are using West Europe and still having the issue.

Exactly!!!
I described it in a previous comment: https://github.com/Azure/api-management-developer-portal/issues/822#issuecomment-673327948

**Comment by LockTar** [comment]
Why closed? Issues are still there...

**Comment by azaslonov** [comment]
Looks like it was auto-closed because of PR that associated with it.

**Comment by azaslonov** [comment]
@LcokTar, after the last hotfix I can repro this anymore on any of my services. Can you please:
1. Ensure you have re-published it;
2. Send service name and network traces to apimportalfeedback@microsoft.com if the issue still there (we need traces from the moment you press sign-in to a one or to loop reloads);

**Comment by olandese** [comment]
> Hi @olandese, backend hasn't been deployed to West Europe yet, but it looks like this bug affects only specific services, so, to make sure this is the same case, could you please capture network traces into HAR file and send it to us [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com)?

Hi @azaslonov ,

I just sent an email with the HAR files and the name of the instances where we are have isues with.

**Comment by azaslonov** [comment]
Thanks, we'll look into this.

**Comment by LockTar** [comment]
> @LcokTar, after the last hotfix I can't repro this anymore on any of my services. Can you please:
> 
> 1. Ensure you have re-published it;
> 2. Send service name and network traces to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com) if the issue still there (we need traces from the moment you press sign-in to a one or to loop reloads);

@olandese and I work both on the same 4 instances (with the same issue) sow you have our traces now.

**Comment by butsona** [comment]
has this been rolled out globally. The portal is still not refreshing after login. We still have to manually refresh the page to complete login. We are using managed portal in uk south

**Comment by tomilaakkonen** [comment]
Any update on this?

@butsona how do you manually refresh? At least for me, f5 after login isn't working. Also clicking on the navigation bar doesn't do any difference.

**Comment by azaslonov** [comment]
UPDATE: The issue has been fixed. We're rolling out a hotfix for the backend. It should land everywhere this week. Thank you for patience everyone.

**Comment by tomilaakkonen** [comment]
At least in West Europe, we haven't got any updates/hotfixes.

**Comment by AnRei123** [comment]
Issue still exists at our location (West Europe). I am still not able to sign in to my published websites. Any news?

**Comment by AnRei123** [comment]
2 further Dev instances have been effected now. Seems that someone has by chance pressed the "publish" buttons for these instances. Please urgently come up with a fix!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by azaslonov** [comment]
@AnRei123, can you send us your service names?
We could try to prioritize them.

**Comment by AnRei123** [comment]
Here the names of the API Management service names:
- apiteamplaydeploytest
- apiteamplaydev

**Comment by azaslonov** [comment]
@AnRei123, can you please give it a try now?

**Comment by ErikMogensen** [comment]
It looks like we have the same problem with our instance in West Europe which has: 
"PortalVersion":"202009011445", 
"CodeVersion":"20200901084820",
"Version":"0.13.1048.0".

Our instance in West Central US also seems to have this problem. It has this version information:
"PortalVersion": "202008260847",
"CodeVersion": "20200812080849",
"Version": "0.13.1056.0"

It seems to be an unrelated problem that the CodeVersion is not updated for the instances in West Central US. I have created two cases with Azure Support this summer to get it updated. At those times the whole region had not been updated. Should I create a third case to get West Central US updated or will it be updated automatically?

**Comment by tgossler** [comment]
The the Chrome browser Application session storage I'm see "Adal" values (see screenshot), and in the Azure Portal I'm seeing a warning that from June 2020 ADAL is not updated and supported anymore. Could it be that there is a problem?

![image](https://user-images.githubusercontent.com/57985062/92003545-759b7180-ed41-11ea-889c-bc3e55d647cd.png)

![image](https://user-images.githubusercontent.com/57985062/92003692-a085c580-ed41-11ea-9344-a975b7533434.png)

**Comment by AnRei123** [comment]
Retested the two API Management services I mentioned above again:

- apiteamplaydeploytest: now WORKING again - thank you!

- apiteamplaydev: still NOT working

**Comment by azaslonov** [comment]
@AnRei123, the codebase is same for both service, so I suspect there is something cached. Can you please try to reset it:
![image](https://user-images.githubusercontent.com/2320302/92023215-5127a100-ed11-11ea-9ec0-92819b3800f3.png)

If still doesn't help, please capture Network traces into HAR file: the login attempt itself and several reload; and send it to apimportalfeedback@microsoft.com

**Comment by AnRei123** [comment]
For the apiteamplaydev service, the published portal is still not working even after performing all the following steps:
-	Clearing the browser cache
-	Clearing the storage for the unregister service worker options on the application tab card
-	Closing and reopening the browser 
-	Republishing again

@azaslonov: I have sent you the HAR file per email.

**Comment by AnRei123** [comment]
For the following internal APIM services the sign-in and routing to the homepage via the portal web URL is also not working:
- apiteamplayuxsource
- apiteamplayuxplayground
- apiteamplayuxdefaults
Could you also fix the issues for these services?

**Comment by azaslonov** [comment]
Hi everyone, can you please re-publish and try again now?

**Comment by tgossler** [comment]
Great, it seems to be working now for us :-)

One thing I had to change in one of our instances was the homepage URL. It was set to the /signin URL as suggested in the tooltip (which is a bit confusing) which resulted in landing on the signin page every time again after sign-in. But this was not the case in other instances where it is now working also.

**Comment by ErikMogensen** [comment]
Yes @azaslonov, we are now able to log in to both of the portals we couldn't log in to previously. 👍

**Comment by AnRei123** [comment]
Thank you for solving this issue! Our portal sign-in works again as expected. Great work!

**Comment by azaslonov** [comment]
Thanks everyone for confirmation and your great patience.
